### ISSUE TITLE
Images rendering incorrect

### ISSUE THREAD

**Issue by mtt87** [CharlesMangwa/react-native-simple-markdown#12] opened 2016-10-25 11:22 UTC
Hi, I noticed that if I try to style the `paragraph` with `lineHeight` or changing the `fontSize` I get images above the text and they are incorrectly rendered.

Do you have an idea why this is happening?

Thank you 😄 

![screen shot 2016-10-25 at 12 19 28](https://cloud.githubusercontent.com/assets/2150927/19684124/75c97836-9aad-11e6-98c4-ffbaaa3c9d03.png)

Without the `lineHeight` property
![screen shot 2016-10-25 at 12 21 55](https://cloud.githubusercontent.com/assets/2150927/19684167/a809c6a2-9aad-11e6-87f5-0ece72a2829f.png)

**Comment by CharlesMangwa** [comment] 2016-10-29 08:24
Hi @mtt87! I just tried to reproduce your bug with 2 images, but I couldn't, here's the output: 
<img width="487" alt="capture d ecran 2016-10-29 a 10 19 47" src="https://cloud.githubusercontent.com/assets/8975443/19828230/5d443d8e-9dc1-11e6-85d7-e29bcdd5d32c.png">

Did you apply another style that could be interfering with it?

**Comment by mtt87** [comment] 2016-11-01 10:13
These are the styles I'm applying:
```js
const stylesMarkdown = {
  image: {
    width: Dimensions.get('window').width - 30,
    height: 300,
    resizeMode: 'contain',
    marginTop: 15,
    marginBottom: 15,
    flex: 1,
  },
  paragraph: {
    fontFamily: 'Roboto',
    // fontSize: 14,
    // lineHeight: 19,
  },
};
```

**Comment by CharlesMangwa** [comment] 2016-11-01 20:27
One of the reasons could be `resizeMode`. For the time being, you have to set it as a normal rule like `image` or `paragraph`. But by default it's set at 'contain' so you don't need to define it there.
Also: did you try to remove the `flex: 1`? Considering that you've already set a width & height, this is maybe not useful. Tell me if it helps!

**Comment by mtt87** [comment] 2016-11-08 22:32
I'm gonna try this tomorrow, sorry for the delay 😄 I was building other features

**Comment by mtt87** [comment] 2016-11-09 17:49
No way, still it happens (only with `lineHeight`)
As reference this is the full code of the page
```es6
import React from 'react';
import {
  StyleSheet,
  Text,
  ScrollView,
  Dimensions,
} from 'react-native';
import Markdown from 'react-native-simple-markdown';
import moment from 'moment';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    marginTop: 65,
    marginBottom: 55,
    flexDirection: 'column',
  },
  title: {
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333',
  },
});

const stylesMarkdown = {
  image: {
    width: Dimensions.get('window').width - 30,
    height: 300,
    marginTop: 15,
    marginBottom: 15,
  },
  paragraph: {
    fontFamily: 'Roboto',
    fontSize: 15,
    // lineHeight: 19,
  },
};

const SingleEvent = ({ markdown, eventData }) =>
  <ScrollView style={styles.container}>
    <Text style={styles.title}>
      {eventData.title}
    </Text>
    <Text style={{ textAlign: 'center', fontSize: 16, color: '#555' }}>
      {moment(eventData.event_start, 'YYYY-MM-DD HH:mm:ss').format('DD MMM HH:mm')}
    </Text>
    <Text style={{ textAlign: 'center', fontSize: 16, marginBottom: 20, color: '#555' }}>
      {eventData.venue_name}
    </Text>
    <Markdown styles={stylesMarkdown}>
      {markdown}
    </Markdown>
  </ScrollView>;

SingleEvent.propTypes = {
  markdown: React.PropTypes.string,
  eventData: React.PropTypes.shape({
    title: React.PropTypes.string.isRequired,
    event_start: React.PropTypes.string.isRequired,
    venue_name: React.PropTypes.string.isRequired,
  }),
};

export default SingleEvent;

```

**Comment by CharlesMangwa** [comment] 2016-11-27 14:11
Hi @mtt87! Sorry for the delay! Do you still have the same problem?

**Comment by mtt87** [comment] 2016-11-28 17:35
@CharlesMangwa Yes in the end I've submitted the app without that change.
Can you spot something strange in my code? 😄

**Comment by CharlesMangwa** [comment] 2016-11-28 18:06
@mtt87 I didn't spot anything that could cause this issue 😕… I'll try again to reproduce it and fix it asap!

**Comment by CharlesMangwa** [comment] 2016-12-04 02:02
Closing issue #12

**Closed by CharlesMangwa** 2016-12-04 02:02 UTC
Labels: bug
