### ISSUE TITLE
Markdown image size is incorrect

### ISSUE THREAD

**Issue by ssmlee04** [CharlesMangwa/react-native-simple-markdown#8] opened 2016-10-10 12:04 UTC
When I was trying to display this image

![](http://i.stack.imgur.com/5elrP.jpg)

The screen seems to display only the center of the image for some reason
![](http://i.stack.imgur.com/hXNX6.jpg)

Is there something that I did wrong?

**Comment by CharlesMangwa** [comment] 2016-10-10 12:12
Hi! Can you show me your code plz? I have an idea about what could be the problem.

**Comment by ssmlee04** [comment] 2016-10-10 12:15
```
var str = "![](https://d1rnv32spgedkm.cloudfront.net/image%2Fde3%2Fa6b%2F650%2Fe26cf40afb5ded4.jpg)

return <Markdown styles={styles}>
          { content }
        </Markdown> 
```

And I think that's basically it.

**Comment by CharlesMangwa** [comment] 2016-10-10 12:18
You're displaying `content` but it doesn't correspond to the variable `str` which contains the URL

**Comment by ssmlee04** [comment] 2016-10-10 12:19
It's a typo. I just edited it. Sorry..

**Comment by CharlesMangwa** [comment] 2016-10-10 13:06
OK I got it: the issue is on my side. I have to set the `resizeMode` prop of the `Image` element, and I think it will be `cover` or `contain`.
The problem is the margin though. With `cover` you have no margin, but the image is cropped: 
<img width="320" alt="capture d ecran 2016-10-10 a 15 03 58" src="https://cloud.githubusercontent.com/assets/8975443/19237019/cdfe5cce-8efa-11e6-8040-433534fb5df0.png">
With the `contain` prop you have this huge margin depending on the size of the picture: 
<img width="320" alt="capture d ecran 2016-10-10 a 15 00 59" src="https://cloud.githubusercontent.com/assets/8975443/19236944/618cbe46-8efa-11e6-9d87-4d20a7738823.png">

What do you think about it?

**Comment by ssmlee04** [comment] 2016-10-10 13:20
I think it's all fine depends on the use case. However do you think maybe pass something like image style into `<Markdown >` is a good idea?

**Comment by CharlesMangwa** [comment] 2016-10-10 13:23
Well it wouldn't work though because `resizeMode` is handle by `<Image />` props, not by its style

**Comment by ssmlee04** [comment] 2016-10-10 13:40
I was kind of thinking maybe something like `{resizeMode==='contain' && <Image resizeMode={'contain'} /> || <Image resizeMode={'cover'} />}`.

**Comment by CharlesMangwa** [comment] 2016-10-10 16:06
Oh ok! Sorry I didn't get you. For the time being, it seems to be a good idea: I just implemented it, you can update with `npm i -S react-native-simple-markdown`. Tell me if it's ok!

**Comment by ssmlee04** [comment] 2016-10-11 12:49
For those images whose height is greater than width the output seems to be weird..

![](https://i.stack.imgur.com/Luv8P.jpg)

**Comment by CharlesMangwa** [comment] 2016-10-11 13:33
Your image seems to be the same here:
![](http://i.stack.imgur.com/5elrP.jpg)
and here:
![](https://i.stack.imgur.com/Luv8P.jpg)

Where's the differences plz?

**Comment by ssmlee04** [comment] 2016-10-11 14:23
I guess I can align the first (red) image to the left by myself. Think normally markdown images wouldn't have anything to do with alignments but I guess I can do something from my side anyways. :) thanks!

**Comment by CharlesMangwa** [comment] 2016-10-12 07:05
Your welcome!

**Comment by CharlesMangwa** [comment] 2016-10-12 07:08
Closing issue #08

**Closed by CharlesMangwa** 2016-10-12 07:08 UTC
