### ISSUE TITLE
Updating image height dynamically doesn't work on Android

### ISSUE THREAD

**Issue by shafy** [CharlesMangwa/react-native-simple-markdown#22] opened 2016-12-31 13:47 UTC
I am rendering markdown with images and have a rule for a custom image component. It calculates the height of the image based on the screen width and updates the style in the image accordingly. While this works perfectly on iOS, it doesn't update the image height on Android. I can see in the console that the code works and updates the state, but somehow the visible image is not updated.

Updating image height without markdown works, so this is not the issue (I use my custom image component outside markdown and it works).

Here is my code:
Markdown rule for custom image component:
```
...
 <Markdown styles={markdownStyles}
            rules={{
              image: {
                react: (node, output, state) => (
                  <ArticleImage
                    key={state.key}
                    source={node.target}
                  />
                ),
              },
            }}
          >
            {this.state.articleContent}
          </Markdown>
...

const markdownStyles = {
  view: {
    backgroundColor: '#FFFFFF',
    width: width,
  },
  heading1: {
    fontSize: 24,
    color: '#000000',
    fontWeight: '400',
    paddingLeft: PADDING_RIGHT_AND_LEFT,
    paddingRight: PADDING_RIGHT_AND_LEFT,
    marginBottom: 15,
    marginTop: 10,
  },
  paragraph: {
    paddingLeft: PADDING_RIGHT_AND_LEFT,
    paddingRight: PADDING_RIGHT_AND_LEFT,
    fontSize: 16,
    color: '#000000',
    marginBottom: 20,
    lineHeight: 25,
  },
  blockQuote: {
    marginTop: 20,
    marginBottom: 20,
    paddingLeft: PADDING_RIGHT_AND_LEFT,
    paddingRight: PADDING_RIGHT_AND_LEFT,
    width: width-20,
  },
}
```

Custom image component:
```
import React, { Component } from 'react';
import { Image, Dimensions} from 'react-native';

const {height, width}  = Dimensions.get('window');

class ArticleImage extends Component {

  constructor(props) {
    super(props);
    this.state = {currentImageHeight: 0}
  }

  componentWillMount() {
    if (this.props.source != null){
      Image.getSize(this.props.source, (imageWidth, imageHeight) => {
        let aspectRatio = imageWidth / imageHeight
        let currentImageHeight = width / aspectRatio
        this.setState({currentImageHeight: currentImageHeight})
      }, (error) => {
        console.log("Failed to get image size:", error)
      });
    }
  }

  render () {
    return (
      <Image source={{uri: this.props.source}} style={{width: width, height: this.state.currentImageHeight}}/>
      );
  }
}

export default ArticleImage
```

I already tried just having rendering an image without any text (so just `![](URL)`) and it still doesn't update the height. I tried removing all markdown styles. The only thing that works is if I set the image height statically.

Did anyone come across something similar or has an idea what else to try?

**Comment by pippinthegreat** [comment] 2017-01-04 14:07
I ran into the same problem as you, the issue is the image is getting put into a `Text` component ([see here](https://github.com/CharlesMangwa/react-native-simple-markdown/blob/master/rules.js#L141)) - the markdown parser outputs the image inside a paragraph

React native supports nested views inside the `Text` component, [but only on iOS and only if the `View` has a height and width](https://facebook.github.io/react-native/docs/text.html#nested-views-ios-only)

I solved this by overriding the paragraph rule and rendering the paragraph as a `View` rather than `Text`

```
<Markdown
	styles={styles}
	rules={{
		paragraph: {
			react: (node, output, state) => {
				return (<View style={styles.paragraph} key={state.key}>{output(node.content, state)}</View>)
			}
		},
		image: {
			react: (node, output, state) => (
				<ImageComponent
					key={state.key}
					src={node.target}
				/>
			),
		},
	}}>
	{this.props.children}
</Markdown>
```

and the styles:

```
paragraph: {
	marginBottom: 10,
	flexWrap: 'wrap',
	flexDirection: 'row',
	alignItems: 'flex-start',
	justifyContent: 'flex-start',
},
```

**Comment by shafy** [comment] 2017-01-19 14:20
thanks @pippinthegreat
In the meantime I solved the problem by writing the aspect ratio of the images in the URL (it's possible because I only load images from my server). But this is good to know if I change this in the future.

But actually it helps me with another issue I was having: When setting a different line height in the text, in Android it breaks the images (they just go under the text). I believe this is also because the image is rendered as Text. I will render it as View and see if this solves my issue.

**Comment by CharlesMangwa** [comment] 2017-02-02 06:50
Hi guys! Sorry for the late reply, hope you fixed your problem! I've been really busy this last couple of days, but I'm planning something new within the next weeks that should resolve this kind of issues 👍

Closing issue #22

**Closed by CharlesMangwa** 2017-02-02 06:50 UTC
Labels: bug

**Comment by shafy** [comment] 2017-02-04 18:05
Sounds good. Post here to let me know when you've got something new 👍  And keep up the good work!
